"""
Django settings for Demo project.

Generated by 'django-admin startproject' using Django 2.2.1.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
# __file__当前文件的路径
# abspath绝对路径
# dirname文件夹的目录
# BASE_DIR django剔骨的项目的根目录，方便我们使用
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '%*jn=s2*4ze()c&w3+3(g@ti^33bwy^@)nl17$q&dc-g!m(@i4'

# SECURITY WARNING: don't run with debug turned on in production!
# debug模式
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
# 注册子应用
# django中的功能主键以app的形式存在
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'Article',
    'ckeditor',
    'ckeditor_uploader',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Demo.urls'
# 模板的配置
TEMPLATES = [
    {
        # 使用的模板引擎
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  #django的模板引擎
        # 模板文件的目录，是一个列表
        'DIRS': [os.path.join(BASE_DIR,"templates")],
        # APP_DIRS 设置是否在子应用中是否自动寻找模板
        'APP_DIRS': True,
        # 是一些针对后端的设置
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Demo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases
# 数据库的配置
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
#     }
# }
# 使用mysql数据库
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST':"127.0.0.1",
        'USER':"root",
        'PASSWORD':"root",
        'PORT':"3306",
        'NAME':"ormdemo"  ##数据库的名字

    }
}

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/
# 语言设置
LANGUAGE_CODE = 'zh-hans'
#时区
TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True
## 是否使用默认时区
# True 使用django内置的时区
# flase 使用设置的时区
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/
# 静态文件的配置
# 静态文件的路由
STATIC_URL = '/static/'
# 静态文件的目录地址
STATICFILES_DIRS=(   #是个元祖
    os.path.join(BASE_DIR,"static"),
)

# 增加媒体文件的配置
MEDIA_URL='/media/'
# 文件上传路径
MEDIA_ROOT=os.path.join(BASE_DIR,'static')

##配置ckeditor的一些设置
## 基于ckeditor 的上传地址
CKEDITOR_UPLOAD_PATH = "static/upload"
## 上传图片使用的模块
CKEDITOR_IMAGE_BACKEND = "pillow"
